-- SECTION01 테이블 구조를 만드는 CREATE TABLE 문
-- CREATE => 오브젝트 생성
-- VAR -> VARIABLE. 데이터의 길이가 일정하지 않을 경우 사용. 가변적. 최대 길이는 지정해준다. 입력된 데이터의 크기에따라 최대 길이 내에서 가변적이다.
-- CHAR -> 입력된 데이터의 길이가 최대치만큼 되지 않더라도 최대 크기로 고정된다. 주민번호같이 크기가 변하지 않는 컬럼들에 사용
-- NVARCHAR -> 한글, 영어 전부 한 문자에 2BYTES. UNICODE
-- CLOB -> 
-- BLOB -> 
CREATE TABLE MEMBER(   
  MID VARCHAR(10) NOT NULL,              
  MNAME VARCHAR(10) NOT NULL,
  MAGE NUMBER(3,0) NULL,
  MBIRTH DATE NULL
);


CREATE TABLE BOARD(
  BNO NUMBER(10,0) NOT NULL,
  BTITLE VARCHAR(100) NOT NULL,
  BCONTENT VARCHAR(4000) NOT NULL,
  BWRITER VARCHAR(10) NOT NULL,
  BHITCOUNT NUMBER(5,0),
  BDATE DATE
);

-- SECTION02 테이블의 구조를 변경하는 ALTER TABLE 문
ALTER TABLE MEMBER ADD EMAIL VARCHAR(100) NULL;
ALTER TABLE MEMBER MODIFY EMAIL VARCHAR(50);

-- 삭제
ALTER TABLE MEMBER DROP COLUMN EMAIL;

-- SECTION03 테이블명을 변경하는 RENAME 문
ALTER TABLE MEMBER RENAME TO MEMBER2;


-- SECTION04 테이블 삭제하는 DROP TABLE 문
DROP TABLE MEMBER;
DROP TABLE BOARD;

SELECT * FROM MEMBER WHERE MID='USER1';

SELECT * FROM BOARD WHERE BNO=1;




