-- SECTION04 유일한 값만 허용하는 UNIQUE 제약 조건
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
  MID VARCHAR(10) UNIQUE NOT NULL,
  MNAME VARCHAR(10) NOT NULL,
  MAGE NUMBER(3) NULL,
  MEMAIL CHAR(50) UNIQUE NULL,
  MBIRTH DATE NULL  
);

INSERT INTO MEMBER VALUES('USER1', '사용자1', 25, 'USER1@SW.COM', SYSDATE);
INSERT INTO MEMBER VALUES('USER2', '사용자2', 25, 'USER2@SW.COM', SYSDATE);
INSERT INTO MEMBER VALUES('USER3', '사용자3', 25, NULL, SYSDATE);
INSERT INTO MEMBER VALUES('USER4', '사용자4', 25, NULL, SYSDATE);


-- SECTION06 데이터 구분을 위한 PRIMARY KEY 제약조건
-- UNIQUE + NOT NULL
-- 한 테이블 당 1개만 설정 가능
-- 행을 구별하는 식별값으로 사용
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
  MID VARCHAR(10) PRIMARY KEY,
  MNAME VARCHAR(10) NOT NULL,
  MAGE NUMBER(3) NULL,
  MEMAIL CHAR(50) UNIQUE NULL,
  MBIRTH DATE NULL  
);

-- SECTION07 참조 무결성을 위한 FOREIGN KEY 제약조건
-- 외부 테이블의 PK 값만 참조할 수 있도록 함
DROP TABLE BOARD;

CREATE TABLE BOARD(
  BNO NUMBER(10,0) PRIMARY KEY,
  BTITLE VARCHAR(100) NOT NULL,
  BCONTENT VARCHAR(4000) NOT NULL,
  BWRITER VARCHAR(10) REFERENCES MEMBER(MID),
  BHITCOUNT NUMBER(5,0),
  BDATE DATE
);

INSERT INTO BOARD VALUES(1, '제목1', '내용1', 'USER1', 0, SYSDATE);
INSERT INTO BOARD VALUES(2, '제목2', '내용2', 'USER2', 0, SYSDATE);


-- SECTION08 CHECK 제약조건
DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
  MID VARCHAR(10) UNIQUE NOT NULL,
  MNAME VARCHAR(10) NOT NULL,
  MAGE NUMBER(3) CHECK(MAGE>=0 AND MAGE<150),
  MSEX VARCHAR(10) CHECK(MSEX IN('남자', '여자')),
  MEMAIL CHAR(50) UNIQUE NULL,
  MBIRTH DATE NULL  
);

INSERT INTO MEMBER VALUES('USER1', '사용자1', 25, '남자', 'USER1@SW.COM', SYSDATE);
INSERT INTO MEMBER VALUES('USER2', '사용자1', 200, '여자', 'USER1@SW.COM', SYSDATE);   -- 체크 제약조건(TESTER1.SYS_C0010961)이 위배
INSERT INTO MEMBER VALUES('USER3', '사용자1', NULL, NULL, 'USER1@SW.COM', SYSDATE);    -- 체크 제약조건(TESTER1.SYS_C0010961)이 위배
INSERT INTO MEMBER VALUES('USER4', '사용자1', 30, '중성', 'USER1@SW.COM', SYSDATE);    -- 체크 제약조건(TESTER1.SYS_C0010961)이 위배


-- SECTION09 DEFAULT 제약조건
DROP TABLE BOARD;

CREATE TABLE BOARD(
  BNO NUMBER(10) PRIMARY KEY,
  BTITLE VARCHAR(100) NOT NULL,
  BCONTENT VARCHAR(4000) NOT NULL,
  BWRITER VARCHAR(10) NOT NULL,
  BHITCOUNT NUMBER(5) DEFAULT 0,
  BKIND VARCHAR(15) DEFAULT '자유',
  BDATE DATE
);

INSERT INTO BOARD VALUES(1, '제목1', '내용1', 'USER1', 0, '자유', SYSDATE);
INSERT INTO BOARD VALUES(2, '제목2', '내용2', 'USER2', DEFAULT, DEFAULT, SYSDATE);
INSERT INTO BOARD(BNO, BTITLE, BCONTENT, BWRITER) VALUES(3, '제목', '내용', 'USER3');  -- DEFAULT 가 설정된 컬럼은 값을 주지 않아도 DEFAULT값이 들어간다.


-- SECTION05 컬럼 레벨로 제약 조건 설정
DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
  MID VARCHAR(10) CONSTRAINT PK_MEMBER_MID PRIMARY KEY,     -- PK_MEMBER_MID => CONSTRAINT_NAME 지정. CONSTRAINT_NAME 을 지정하지 않으면 SYS_XXXX 로 만들어진다.
  MNAME VARCHAR(10) NOT NULL                                -- NOT NULL 은 컬럼 레벨에서만 지정할 수 있다.
);

CREATE TABLE MEMBER(
  MID VARCHAR(10) CONSTRAINT PK_MEMBER_MID PRIMARY KEY,
  MAGE VARCHAR(10) CONSTRAINT CH_MEMBER_MAGE CHECK(MAGE>=0 AND MAGE<150)
);

CREATE TABLE BOARD(
  BNO NUMBER(10) CONSTRAINT PK_BOARD_BNO PRIMARY KEY,
  BWRITER VARCHAR(10) CONSTRAINT FK_BOARD_BWRITER REFERENCES MEMBER(MID)
);

-- SECTION10 테이블 레벨로 제약 조건 설정
CREATE TABLE MEMBER(
  MID VARCHAR(10) NOT NULL,
  MNAME VARCHAR(10) NOT NULL,
  CONSTRAINT PK_MEMBER_MID PRIMARY KEY(MID)
);

CREATE TABLE MEMBER(
  SSN1 VARCHAR(6) NOT NULL,
  SSN2 VARCHAR(7) NOT NULL,
  MAGE VARCHAR(10) NOT NULL,
  CONSTRAINT PK_MEMBER_SSN PRIMARY KEY(SSN1, SSN2),   -- 복합키
  CONSTRAINT CH_MEMBER_MAGE CHECK(MAGE>=0 AND MAGE<150)
);

CREATE TABLE BOARD(
  BNO NUMBER(10), 
  BWRITER VARCHAR(10),
  CONSTRAINT PK_BOARD_BNO PRIMARY KEY(BNO),
  CONSTRAINT FK_BOARD_BWRITER FOREIGN KEY(BWRITER) REFERENCES MEMBER(MID)
);

-- SECTION11 제약조건 변경하기
DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
  SSN1 VARCHAR(6) NOT NULL,
  SSN2 VARCHAR(7) NOT NULL,
  MAGE VARCHAR(10) NOT NULL
);

CREATE TABLE BOARD(
  BNO NUMBER(10), 
  BWRITER VARCHAR(10)
);

-- 11.1 제약조건 추가하기
ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER_SSN PRIMARY KEY(SSN1, SSN2);
ALTER TABLE MEMBER ADD CONSTRAINT CH_MEMBER_MAGE CHECK(MAGE>=0 AND MAGE<150);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD_BNO PRIMARY KEY(BNO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_BWRITER FOREIGN KEY(BWRITER) REFERENCES MEMBER(MID);

-- 11.3 제약조건 제거하기
DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
  SSN1 VARCHAR(6) NOT NULL,
  SSN2 VARCHAR(7) NOT NULL,
  MAGE VARCHAR(10) NOT NULL,
  CONSTRAINT PK_MEMBER_SSN PRIMARY KEY(SSN1, SSN2),  
  CONSTRAINT CH_MEMBER_MAGE CHECK(MAGE>=0 AND MAGE<150)
);

ALTER TABLE MEMBER DROP PRIMARY KEY;  -- PK 제거시에는 이름이 필요없다.
ALTER TABLE MEMBER DROP CONSTRAINT CH_MEMBER_MAGE;  -- 한 테이블에 여러개의 CHECK 가 들어가기 때문에 CONSTRAINT 명을 입력해준다.


-- SECTION12 제약조건의 비활성화와 CASCADE
DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
  MID VARCHAR(10) CONSTRAINT PK_MEMBER_MID PRIMARY KEY,
  MAGE VARCHAR(10) CONSTRAINT CH_MEMBER_MAGE CHECK(MAGE>=0 AND MAGE<150)
);

CREATE TABLE BOARD(
  BNO NUMBER(10) CONSTRAINT PK_BOARD_BNO PRIMARY KEY,
  BWRITER VARCHAR(10) CONSTRAINT FK_BOARD_BWRITER REFERENCES MEMBER(MID)
);

-- 12.1 제약 조건의 비활성화
ALTER TABLE BOARD DISABLE PRIMARY KEY;

-- 12.2 제약 조건의 활성화
ALTER TABLE BOARD ENABLE PRIMARY KEY;

-- 12.3 CASCADE
ALTER TABLE MEMBER DISABLE PRIMARY KEY;           -- BOARD에서 참조하고 있는 값이 있어서 DISABLE 할 수 없다.
ALTER TABLE MEMBER DISABLE PRIMARY KEY CASCADE;   -- CASCADE 하면 BOARD 에서 참조하고 있는 FK 가 먼저 DISABLE 되고 MEMBER의 PK 가 DISABLE 된다.
ALTER TABLE MEMBER ENABLE PRIMARY KEY;

ALTER TABLE BOARD ENABLE CONSTRAINT FK_BOARD_BWRITER; -- DISABLE 된 FK 는 따로 활성화 시켜줘야 한다.

-- 12.4 ON DELETE CASCADE
INSERT INTO MEMBER VALUES('USER1', 25);
INSERT INTO BOARD VALUES(1, 'USER1');
INSERT INTO BOARD VALUES(2, 'USER1');

DELETE FROM BOARD WHERE BWRITER='UESR1';
DELETE FROM MEMBER WHERE MID='USER1';   -- BOARD에서 참조값이 있어서 삭제되지 않는다.


DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
  MID VARCHAR(10) CONSTRAINT PK_MEMBER_MID PRIMARY KEY,
  MAGE VARCHAR(10) CONSTRAINT CH_MEMBER_MAGE CHECK(MAGE>=0 AND MAGE<150)
);

CREATE TABLE BOARD(
  BNO NUMBER(10) CONSTRAINT PK_BOARD_BNO PRIMARY KEY,
  BWRITER VARCHAR(10) CONSTRAINT FK_BOARD_BWRITER REFERENCES MEMBER(MID) ON DELETE CASCADE  -- 참조하고 있는 MEMBER(MID) 가 삭제되면 자동적으로 같이 삭제
);

INSERT INTO MEMBER VALUES('USER1', 25);
INSERT INTO BOARD VALUES(1, 'USER1');
INSERT INTO BOARD VALUES(2, 'USER1');

DELETE FROM MEMBER WHERE MID='USER1';     -- ON DELETE CASCADE 옵션에 의해 BOARD 에서 참조하고 있는 값도 같이 삭제된다.


























