-- 행 순번 붙이기
SELECT ROWNUM, BNO, BTITLE
  FROM BOARD
 ORDER BY BNO;  -- ROWNUM은 FROM 까지만 영향을 미친다. 정렬은 되지 않는다

SELECT ROWNUM, BNO, BTITLE
  FROM ( SELECT BNO, BTITLE FROM BOARD ORDER BY BNO);

SELECT ROWNUM, BNO, BTITLE
  FROM ( SELECT BNO, BTITLE FROM BOARD ORDER BY BNO DESC);

-- 최근 삽입된 행 5개를 가져와라
SELECT ROWNUM, BNO, BTITLE
  FROM ( SELECT BNO, BTITLE FROM BOARD ORDER BY BNO DESC)
 WHERE ROWNUM <= 5;     -- WHERE 절이 FALSE 가 될때 까지 번호를 매긴다.
 
SELECT ROWNUM, BNO, BTITLE
  FROM ( SELECT BNO, BTITLE FROM BOARD ORDER BY BNO DESC)
 WHERE ROWNUM > 5000;   -- 1부터 조건절과 비교하기 때문에 FALSE가 되어 조회되지 않는다. 

-- 11번부터 20번까지 조회
SELECT RN, BNO, BTITLE
FROM (
      SELECT ROWNUM AS RN, BNO, BTITLE
        FROM ( SELECT BNO, BTITLE FROM BOARD ORDER BY BNO DESC)
       WHERE ROWNUM <= 20
      )
 WHERE RN >= 11;
 
-- 1페이지에 10개씩 구성하고, N번째 페이지를 가져와라
-- 1~10 = 1PAGE, 11~20 = 2PAGE, 21~30 = 3PAGE, ((N-1)*ROWSPERPAGE+1) ~ (N*ROWSPERPAGE) = NPAGE
SELECT RN, BNO, BTITLE
FROM (
      SELECT ROWNUM AS RN, BNO, BTITLE
        FROM ( SELECT BNO, BTITLE FROM BOARD ORDER BY BNO DESC)
       WHERE ROWNUM <= (N*10)
      )
 WHERE RN >= ((N-1)*10+1);
 
 
SELECT RN, BNO, BTITLE, BCONTENT, BWRITER, BHITCOUNT, BDATE
  FROM (
	      SELECT ROWNUM AS RN, BNO, BTITLE, BCONTENT, BWRITER, BHITCOUNT, BDATE
	        FROM ( SELECT BNO, BTITLE, BCONTENT, BWRITER, BHITCOUNT, BDATE FROM BOARD ORDER BY BNO DESC)
	       WHERE ROWNUM <= 2 * 10
      )
WHERE RN >= ((2-1) * 10+1);
 
 
 
 
 
 
 