-- CH13 시퀀스와 인덱스
-- SECTION01 시퀀스 생성
CREATE SEQUENCE SEQ_1;

-- 다음 수 얻기
SELECT SEQ_1.NEXTVAL FROM DUAL;

-- 현재 부여된 마지막 번호
SELECT SEQ_1.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQ_2
  START WITH 101
  INCREMENT BY 10
  MAXVALUE 1000
  NOCYCLE
  NOCACHE;

SELECT SEQ_2.NEXTVAL FROM DUAL;

DROP SEQUENCE SEQ_1;


-- SECTION04 인덱스 개요
-- 검색 속도를 빠르게 하기위해 생성, WHERE 절에서 조건으로 많이 사용되는 컬럼
-- CREATE INDEX => 중복을 허용하는 컬럼에 생성
-- CREATE UNIQUE INDEX => 중복을 허용하지 않는 컬럼에 생성(PK, UNIQUE)
SET TIMING ON;
SELECT * FROM BOARD WHERE BNO = 9333;

CREATE INDEX IDX_BOARD_BTITLE ON BOARD(BTITLE);   --조건에 자주 사용하는 컬럼의 인덱스를 생성한다.

DROP INDEX IDX_BOARD_BTITLE;

CREATE UNIQUE INDEX SEQ_BOARD_BNO ON BOARD(BNO);
SELECT * FROM BOARD WHERE BNO = 9333;
DROP INDEX SEQ_BOARD_BNO;











