-- 첫번째 미션
-- 1
SELECT ENAME, SAL, TO_CHAR(HIREDATE, 'MM/DD/YYYY') HIREDATE
  FROM EMP;

-- 2
SELECT DEPTNO 부서번호, DNAME 부서명 FROM DEPT;

-- 3
SELECT DISTINCT JOB FROM EMP;

-- 두번째 미션
-- 1
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL <= 300;
-- 2
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME = '오지호';
-- 3 
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL = 250 OR SAL = 300 OR SAL = 500;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL IN(250, 300, 500);

-- 4
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL != 250 AND SAL != 300 AND SAL != 500;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL NOT IN (250, 300, 500);

-- 세번째 미션
-- 1
SELECT EMPNO, ENAME FROM EMP WHERE ENAME LIKE '김%' OR ENAME LIKE '%기%';

-- 2
SELECT * FROM EMP WHERE MGR IS NULL;

-- 3
SELECT EMPNO, ENAME, JOB, TO_CHAR(HIREDATE, 'YYYY/MM/DD') FROM EMP ORDER BY HIREDATE DESC;

-- 4
SELECT DEPTNO, EMPNO, ENAME, JOB, TO_CHAR(HIREDATE, 'YYYY/MM/DD') FROM EMP ORDER BY DEPTNO, HIREDATE;




