-- CH3 QUIZ
-- 1
SELECT * FROM EMP WHERE MOD(EMPNO, 2)=1;

-- 2
SELECT HIREDATE, SUBSTR(HIREDATE,1,2) 년도,
                 SUBSTR(HIREDATE,4,2) 월,
                 SUBSTR(HIREDATE,7,2) 일
FROM EMP;

-- 3
SELECT ROUND(SYSDATE-HIREDATE) 근무일수
  FROM EMP;
  
-- 4
SELECT EMPNO, ENAME, NVL(TO_CHAR(MGR, '9999'), 'CEO') AS "직속상관"
  FROM EMP
 WHERE MGR IS NULL; 

-- 5
DUAL;

-- 6
SELECT SYSDATE+100 FROM DUAL;

-- 7
SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- 8
NVL2(COMM, SAL+COMM, SAL); --COMM 이 NULL 이면 SAL+COMM 아니면 SAL

-- 9
CASE;

-- 10
SYSDATE;


-- CH4 QUIZ
-- 7
SELECT COUNT(*)
  FROM EMP
 WHERE DEPTNO = 30
   AND COMM IS NOT NULL;

-- 8
SELECT MAX(HIREDATE) "가장 최근에 입사한 사원", MIN(HIREDATE) "가장 오래된 사원"
  FROM EMP;

-- 9
SELECT JOB, SUM(SAL)
  FROM EMP
 GROUP BY JOB
 HAVING SUM(SAL) > 300;

-- CH10 QUIZ
-- 1
SELECT ENAME, DNAME
  FROM EMP, DEPT; 
  
-- 2
SELECT ENAME
  FROM EMP MEMBER, EMP MANAGER
 WHERE MEMBER.MANAGER = MANAGER.EMPNO;

-- 11
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO;
 
SELECT E.ENAME, D.DNAME
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO;

-- 12
SELECT E.ENAME, E.HIREDATE
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND D.DNAME = '경리부';

-- 13 
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND JOB = '과장';

-- 14
SELECT WORK.ENAME, WORK.JOB
  FROM EMP WORK, EMP MANAGER
 WHERE WORK.MGR = MANAGER.EMPNO
   AND MANAGER.ENAME = '감우성';
   
-- 15 
SELECT WORK.ENAME, FRIEND.ENAME
  FROM EMP WORK, EMP FRIEND
 WHERE WORK.DEPTNO = FRIEND.DEPTNO
   AND WORK.ENAME != FRIEND.ENAME
   AND WORK.ENAME = '감우성';


-- CH11 QUIZ
-- 8
SELECT ENAME, SAL
  FROM EMP
 WHERE SAL > ANY( SELECT MIN(SAL)
                 FROM EMP
                WHERE JOB = '과장' )
   AND JOB != '과장';

-- 9
UPDATE EMP06
  SET SAL = SAL + 100 
 WHERE DEPTNO = ( SELECT DEPTNO
                    FROM DEPT
                   WHERE LOC = '인천');
-- 10   
DELETE FROM EMP06
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='경리부');

-- 11 
SELECT ENAME, DEPTNO
  FROM EMP
 WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = '이문세')
   AND ENAME != '이문세'; 

-- 12
SELECT *
  FROM EMP
 WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME ='이문세')
   AND ENAME != '이문세';
   
-- 13
SELECT ENAME, SAL
  FROM EMP
 WHERE SAL >= (SELECT SAL FROM EMP WHERE ENAME = '이문세')
   AND ENAME != '이문세';
   
-- 14
SELECT ENAME, DEPTNO
  FROM EMP
 WHERE DEPTNO = ( SELECT DEPTNO FROM DEPT WHERE LOC = '인천');

-- 15
SELECT ENAME, SAL, MGR
  FROM EMP
 WHERE MGR = ( SELECT EMPNO FROM EMP WHERE ENAME = '감우성');

-- 16
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP
 WHERE SAL IN ( SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO );

-- 17 
SELECT DEPTNO, DNAME, LOC
  FROM DEPT
 WHERE DEPTNO IN ( SELECT DEPTNO FROM EMP WHERE JOB = '과장');

-- 18
SELECT ENAME, SAL, JOB
  FROM EMP
 WHERE SAL > ALL ( SELECT MAX(SAL) FROM EMP WHERE JOB='과장');










